name: empathyGenerator

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.0.0
  flutter_tts: ^3.7.0
  speech_to_text: ^6.3.0
  avatar_glow: ^2.0.2
  flutter_screenutil: ^5.6.0
  flutter_easyloading: ^3.0.5
  provider: ^6.0.5
  font_awesome_flutter: ^10.3.0
  flutter_staggered_grid_view: ^0.6.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  get_it: ^7.2.0
  intl: ^0.17.0
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.7.1
  json_annotation: ^4.7.0
  google_sign_in: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
#    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
